# http
@WebLayer_HostAddress = http://localhost:5220

GET {{WebLayer_HostAddress}}/api/genres
Accept: application/json

###
GET {{WebLayer_HostAddress}}/api/genres?PageNumber=1&PageSize=4
Accept: application/json
###

GET {{WebLayer_HostAddress}}/api/genres?PageNumber=2&PageSize=27
Accept: application/json
###
GET {{WebLayer_HostAddress}}/api/genres/4
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/episodes
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/episodes/tt0734542
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/titles
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/titles/tt0108778
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/titles/search?name=The civil war

###

GET {{WebLayer_HostAddress}}/api/persons/nm0000206
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/persons/
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/versions/tt0063929
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/users
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/users/28
Accept: application/json

###

POST {{WebLayer_HostAddress}}/api/users
Content-Type: application/json

{
	"Username": "alexander",
    "Email":"alexander@test.com",
    "PasswordHash":"password"
}

###

DELETE {{WebLayer_HostAddress}}/api/users/47
Content-Type: application/json

### 

GET {{WebLayer_HostAddress}}/api/titlegenre
Content-Type: application/json

### 

PUT {{WebLayer_HostAddress}}/api/users/47
Content-Type: application/json

{
	"Username": "Cesarruac",
    "Email":"testingputting@gmail.com",
    "PasswordHash":"hahahha"
}

###

POST {{WebLayer_HostAddress}}/api/users/login
Content-Type: application/json

{
    "Email": "alexander@test.com",
    "Password":"password"
}

###

GET {{WebLayer_HostAddress}}/api/users/50
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4YW5kZXIiLCJlbWFpbCI6ImFsZXhhbmRlckB0ZXN0LmNvbSIsIlVzZXJJZCI6IjQ5IiwiZXhwIjoxNzYyMzU1OTQ5LCJpc3MiOiJNeVdlYkFwaSIsImF1ZCI6Ik15V2ViQ2xpZW50In0.zKBtrK423Z3BlOiX_qpf8EHeaC4qovOv9AYTvdLb4YI
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0aW5ndGhpcyIsImVtYWlsIjoiZmFzZmFzZmFmQHRlc3QuY29tIiwiVXNlcklkIjoiNTAiLCJleHAiOjE3NjIzODAyMzksImlzcyI6Ik15V2ViQXBpIiwiYXVkIjoiTXlXZWJDbGllbnQifQ.xzUleuY8To1SiLOENarbTTb6xnRJT8mDxcUlhslzew4

###

POST {{WebLayer_HostAddress}}/api/users
Content-Type: application/json

{
  "Username": "testingthis",
  "Email":"fasfasfaf@test.com",
  "PasswordHash":"password"
}

###

POST {{WebLayer_HostAddress}}/api/users/login
Content-Type: application/json

{
  "Email": "fasfasfaf@test.com",
  "Password":"password"
}
