# http
@WebLayer_HostAddress = http://localhost:5220

GET {{WebLayer_HostAddress}}/api/genres
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/genres/1
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/episodes
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/titles
Accept: application/json

###

GET {{WebLayer_HostAddress}}/api/titlesandgenres/tt0108778
Accept: application/json

###
